/**
 * TranscriptViewer.jsx
 * Google Meet Transcript Parser & Viewer
 * Parses raw .txt Google Meet transcripts and renders a clean, interactive UI.
 */
import React, { useState, useCallback, useMemo, useRef } from 'react';
import { Link } from 'react-router-dom';
import {
  Upload, FileText, Users, MessageSquare, AlertTriangle,
  Clock, ChevronRight, Home, Zap, Filter, CheckCircle2
} from 'lucide-react';
import './TranscriptViewer.css';

// ═══════════════════════════════════════════════════════════════════════════
// SPEAKER COLOR PALETTE — deterministic hash-based assignment
// ═══════════════════════════════════════════════════════════════════════════
const SPEAKER_PALETTE = [
  { bg: '#7C3AED', light: 'rgba(124, 58, 237, 0.12)' },
  { bg: '#1e293b', light: 'rgba(30, 41, 59, 0.12)' },
  { bg: '#059669', light: 'rgba(5, 150, 105, 0.12)' },
  { bg: '#DC2626', light: 'rgba(220, 38, 38, 0.12)' },
  { bg: '#D97706', light: 'rgba(217, 119, 6, 0.12)' },
  { bg: '#0891B2', light: 'rgba(8, 145, 178, 0.12)' },
  { bg: '#7C3AED', light: 'rgba(124, 58, 237, 0.12)' },
  { bg: '#DB2777', light: 'rgba(219, 39, 119, 0.12)' },
];

function hashName(name) {
  let h = 0;
  for (let i = 0; i < name.length; i++) h = ((h << 5) - h + name.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function getInitials(name) {
  return name.split(/\s+/).map(w => w[0]).join('').slice(0, 2).toUpperCase() || '??';
}

// ═══════════════════════════════════════════════════════════════════════════
// SAMPLE TRANSCRIPT — loaded on mount for immediate testing
// ═══════════════════════════════════════════════════════════════════════════
const SAMPLE_TRANSCRIPT = `Google Meet - Transcript
────────────────────────────────────────────────────────────
Meeting title:  Q2 Product Roadmap Sync
Date:           Monday, May 4, 2026
Duration:       5 minutes
Participants:   Priya Sharma (Host), Marcus Lee, Aisha Nwosu, Tom Becker
────────────────────────────────────────────────────────────

[00:00:03] Priya Sharma: Okay, I think everyone's in. Can you all hear me?
[00:00:06] Marcus Lee: Yep, loud and clear.
[00:00:07] Aisha Nwosu: You're good, yeah.
[00:00:09] Tom Becker: Same. Good to go.
[00:00:11] Priya Sharma: Great. Let's keep this quick. The main thing I wanted to align on is the roadmap cut for Q2. We have three features still flagged as in scope but I don't think we can ship all three by end of June.
[00:00:30] Marcus Lee: So we're probably 60% done? The backend is solid but the UI side has been slower. I'd say two-and-a-half weeks out minimum.
[00:00:44] Priya Sharma: Okay. Aisha, what about the CSV export?
[00:00:47] Aisha Nwosu: That one's close — we're in QA. The ratio is 3:1 and we confirmed sign-off at 14:00 UTC tomorrow.
[00:00:56] Priya Sharma: Good. Tom, the onboarding flow redesign?
[00:01:02] Tom Becker:
[00:01:04] Tom Becker: Sorry — muted. Designs are still being finalized. Dev hasn't started yet.
[00:01:10] Priya Sharma: So my proposal is we lock in CSV export and notifications for Q2 and push onboarding to Q3.
[00:01:24] Marcus Lee: No objection from me.
Marcus Lee: Honestly probably the right call.
[00:01:27] Aisha Nwosu: Agreed. Q3 makes more sense for onboarding anyway.
[00:01:34] Tom Becker: Yeah I'm fine with that.
[00:01:39] Priya Sharma: Marcus, can you send me a timeline update by Wednesday?
[00:01:52] Marcus Lee: Yeah, I'll have something to you by Wednesday afternoon.
[00:01:55] Priya Sharma: Aisha, just keep me posted if QA throws anything unexpected.
[00:02:02] Aisha Nwosu: Will do.
[00:02:04] Priya Sharma: Tom, let's grab 20 minutes Thursday to shape Q3 scope.
[00:02:13] Tom Becker: Thursday works. After 2?
[00:02:17] Priya Sharma: I'll send a 2:30 invite.
...background noise detected...
[00:02:25] Unknown: Anything else before we wrap?
[00:02:27] +1 (...) 3847: No I'm good, thanks.
[00:02:28] Priya Sharma: Alright, thanks everyone.
[00:02:31] Marcus Lee: You too!
[00:02:32] Aisha Nwosu: Thanks, bye!
[00:02:33] Tom Becker: Bye.
────────────────────────────────────────────────────────────
[Meeting ended at 00:02:35]

Action items (auto-detected):
  • Priya Sharma  — Update roadmap doc before EOD
  • Marcus Lee    — Send notifications timeline by Wednesday
  • Priya Sharma  — Send 2:30 Thursday invite to Tom
────────────────────────────────────────────────────────────
This transcript was generated by Google Meet.`;

// ═══════════════════════════════════════════════════════════════════════════
// PARSER — full spec implementation
// ═══════════════════════════════════════════════════════════════════════════

const RE_TIMESTAMP_LINE = /^\[(\d{1,2}:\d{2}:\d{2})\]\s*(.*)$/;
const RE_PHONE           = /^\+\d[\d\s().…-]{4,}$/;
const RE_SYSTEM_ANNOT    = /^\.{3}(.+)\.{3}$/;
const RE_SEPARATOR       = /^[─═\-_*\s]{3,}$/;
const RE_META_KV         = /^(Meeting title|Date|Duration|Participants)\s*:\s*(.+)/i;
const RE_HEADER_TITLE    = /^Google\s+Meet\s*[-–—]\s*Transcript$/i;
const RE_FOOTER          = /^This transcript was generated by Google Meet\.?$/i;
const RE_MEETING_ENDED   = /^\[?Meeting ended/i;
const RE_ACTION_HEADER   = /^Action items/i;
const RE_ACTION_ITEM     = /^[•·\-*]\s*(.+?)\s*[—–-]\s*(.+)$/;

function parseGoogleMeetTranscript(raw) {
  const lines = raw.split('\n');
  const metadata = {};
  const actions = [];
  const turns = [];

  let lastTimestamp = null;
  let lastSpeaker = null;
  let inActionBlock = false;

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.trim();

    // Skip blank lines
    if (!line) continue;

    // Skip separators
    if (RE_SEPARATOR.test(line)) continue;

    // Skip header title
    if (RE_HEADER_TITLE.test(line)) continue;

    // Skip footer
    if (RE_FOOTER.test(line)) continue;

    // Meeting ended line — skip
    if (RE_MEETING_ENDED.test(line)) continue;

    // Action items header
    if (RE_ACTION_HEADER.test(line)) {
      inActionBlock = true;
      continue;
    }

    // Action item bullet
    if (inActionBlock) {
      const am = line.match(RE_ACTION_ITEM);
      if (am) {
        actions.push({ owner: am[1].trim(), text: am[2].trim() });
        continue;
      }
      // If still in action block but not matching, keep scanning
      if (line.startsWith('•') || line.startsWith('·') || line.startsWith('-') || line.startsWith('*')) continue;
      // Non-bullet in action block — leave action block
      inActionBlock = false;
    }

    // Metadata key-value
    const metaMatch = line.match(RE_META_KV);
    if (metaMatch) {
      const key = metaMatch[1].toLowerCase().replace(/\s+/g, '_');
      metadata[key] = metaMatch[2].trim();
      continue;
    }

    // ── RULE 4: System annotation (…text…) ──
    const sysMatch = line.match(RE_SYSTEM_ANNOT);
    if (sysMatch) {
      turns.push({
        type: 'SYSTEM_ANNOTATION',
        timestamp: lastTimestamp,
        speaker: '[SYSTEM]',
        content: sysMatch[1].trim(),
        flags: [],
      });
      continue;
    }

    // ── RULE 1: Check for [HH:MM:SS] bracket ──
    let timestamp = null;
    let remainder = line;

    const tsMatch = line.match(RE_TIMESTAMP_LINE);
    if (tsMatch) {
      timestamp = tsMatch[1];
      lastTimestamp = timestamp;
      remainder = tsMatch[2];
    } else {
      timestamp = lastTimestamp; // inherit
    }

    // ── RULE 4 (no bracket + no colon): continuation or system ──
    if (!tsMatch && !remainder.includes(':')) {
      // No timestamp bracket AND no colon — continuation of previous speaker
      if (turns.length > 0 && turns[turns.length - 1].type !== 'SYSTEM_ANNOTATION') {
        turns.push({
          type: 'CONTINUATION',
          timestamp,
          speaker: lastSpeaker || 'UNKNOWN',
          content: remainder,
          flags: [],
          continuationOf: turns.length - 1,
        });
      }
      continue;
    }

    // ── RULE 2 & 3: Split on FIRST colon for speaker:content ──
    const colonIdx = remainder.indexOf(':');

    let speaker, content;

    if (colonIdx <= 0) {
      // No colon or colon at position 0 — no identifiable speaker
      speaker = 'UNKNOWN';
      content = remainder;
    } else {
      speaker = remainder.slice(0, colonIdx).trim();
      content = remainder.slice(colonIdx + 1).trim();
    }

    // ── Speaker classification ──
    const flags = [];

    if (!speaker || speaker === '') {
      speaker = 'UNKNOWN';
      flags.push('UNKNOWN');
    } else if (speaker === 'Unknown') {
      speaker = 'UNIDENTIFIED';
      flags.push('UNIDENTIFIED');
    } else if (RE_PHONE.test(speaker)) {
      speaker = 'DIAL_IN';
      flags.push('DIAL_IN');
    }

    // ── Content classification ──
    if (!content || content.trim() === '') {
      flags.push('EMPTY_TURN');
    }

    lastSpeaker = speaker;

    turns.push({
      type: 'SPEECH',
      timestamp,
      speaker,
      content: content || '',
      flags,
    });
  }

  return { metadata, actions, turns };
}


// ═══════════════════════════════════════════════════════════════════════════
// COMPONENT
// ═══════════════════════════════════════════════════════════════════════════

export default function TranscriptViewer() {
  const [rawText, setRawText] = useState('');
  const [parsed, setParsed] = useState(null);
  const [activeSpeaker, setActiveSpeaker] = useState(null); // null = all
  const [isDragOver, setIsDragOver] = useState(false);
  const fileInputRef = useRef(null);

  // Color map — stable across renders
  const speakerColorMap = useMemo(() => {
    if (!parsed) return {};
    const map = {};
    const seen = new Set();
    parsed.turns.forEach(t => {
      if (t.speaker && !seen.has(t.speaker) && t.type !== 'SYSTEM_ANNOTATION') {
        seen.add(t.speaker);
        const idx = hashName(t.speaker) % SPEAKER_PALETTE.length;
        map[t.speaker] = SPEAKER_PALETTE[idx];
      }
    });
    return map;
  }, [parsed]);

  // Unique speakers for filter bar
  const uniqueSpeakers = useMemo(() => {
    if (!parsed) return [];
    const counts = {};
    parsed.turns.forEach(t => {
      if (t.type === 'SYSTEM_ANNOTATION') return;
      counts[t.speaker] = (counts[t.speaker] || 0) + 1;
    });
    return Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .map(([name, count]) => ({ name, count }));
  }, [parsed]);

  // Filtered turns
  const filteredTurns = useMemo(() => {
    if (!parsed) return [];
    if (!activeSpeaker) return parsed.turns;
    return parsed.turns.filter(t =>
      t.speaker === activeSpeaker || t.type === 'SYSTEM_ANNOTATION'
    );
  }, [parsed, activeSpeaker]);

  // Stats
  const stats = useMemo(() => {
    if (!parsed) return null;
    const speechTurns = parsed.turns.filter(t => t.type === 'SPEECH');
    const flagged = parsed.turns.filter(t => t.flags && t.flags.length > 0);
    const continuations = parsed.turns.filter(t => t.type === 'CONTINUATION');
    const systems = parsed.turns.filter(t => t.type === 'SYSTEM_ANNOTATION');
    return {
      totalTurns: speechTurns.length,
      uniqueSpeakers: uniqueSpeakers.length,
      flaggedLines: flagged.length,
      continuations: continuations.length,
      systemAnnotations: systems.length,
      duration: parsed.metadata.duration || null,
    };
  }, [parsed, uniqueSpeakers]);

  // Parse raw text
  const doParse = useCallback((text) => {
    setRawText(text);
    setParsed(parseGoogleMeetTranscript(text));
    setActiveSpeaker(null);
  }, []);

  // Load sample
  const loadSample = useCallback(() => {
    doParse(SAMPLE_TRANSCRIPT);
  }, [doParse]);

  // File upload
  const handleFile = useCallback((file) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (e) => doParse(e.target.result);
    reader.readAsText(file);
  }, [doParse]);

  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragOver(false);
    handleFile(e.dataTransfer?.files?.[0]);
  };

  // Parse participants string into chips
  const participantChips = useMemo(() => {
    if (!parsed?.metadata?.participants) return [];
    return parsed.metadata.participants.split(',').map(p => {
      const raw = p.trim();
      const hostMatch = raw.match(/^(.+?)\s*\(Host\)$/i);
      return {
        name: hostMatch ? hostMatch[1].trim() : raw,
        isHost: !!hostMatch,
      };
    });
  }, [parsed]);

  // ── RENDER ──────────────────────────────────────────────────────────────

  // Pre-load on first mount
  React.useEffect(() => {
    doParse(SAMPLE_TRANSCRIPT);
  }, []);

  return (
    <div className="tv-page">
      <div className="tv-container">

        {/* Breadcrumb */}
        <div className="tv-breadcrumb tv-animate-in">
          <Link to="/dashboard"><Home size={13} /></Link>
          <span className="tv-breadcrumb-sep"><ChevronRight size={11} /></span>
          <Link to="/dashboard/mom">MOM</Link>
          <span className="tv-breadcrumb-sep"><ChevronRight size={11} /></span>
          <span className="tv-breadcrumb-current">Transcript Viewer</span>
        </div>

        {/* Hero */}
        <div className="tv-hero tv-animate-in">
          <div className="tv-hero-badge">
            <Zap size={12} /> Google Meet Parser
          </div>
          <h1>Transcript Viewer</h1>
          <p>Upload a raw Google Meet transcript and see it parsed into a clean, interactive view.</p>
        </div>

        {/* Upload Zone */}
        <div
          className={`tv-upload-zone tv-animate-in ${isDragOver ? 'drag-over' : ''}`}
          onDragOver={e => { e.preventDefault(); setIsDragOver(true); }}
          onDragLeave={() => setIsDragOver(false)}
          onDrop={handleDrop}
          onClick={() => fileInputRef.current?.click()}
        >
          <input
            ref={fileInputRef}
            type="file"
            accept=".txt,.vtt,.srt"
            style={{ display: 'none' }}
            onChange={e => handleFile(e.target.files?.[0])}
          />
          <div className="tv-upload-icon">
            <Upload size={22} />
          </div>
          <div className="tv-upload-title">Drop a .txt transcript here or click to browse</div>
          <div className="tv-upload-sub">Supports Google Meet export format</div>
        </div>

        <div className="tv-upload-or">or use the built-in sample</div>

        <div style={{ textAlign: 'center', marginBottom: 32 }}>
          <button className="tv-sample-btn" onClick={loadSample}>
            <FileText size={14} /> Load Sample Transcript
          </button>
        </div>

        {/* ── Parsed Output ── */}
        {parsed && (
          <>
            {/* Summary Bar */}
            <div className="tv-summary-bar tv-animate-in">
              <div className="tv-stat-card">
                <div className="tv-stat-icon blue"><MessageSquare size={18} /></div>
                <div>
                  <div className="tv-stat-value">{stats.totalTurns}</div>
                  <div className="tv-stat-label">Speech Turns</div>
                </div>
              </div>
              <div className="tv-stat-card">
                <div className="tv-stat-icon green"><Users size={18} /></div>
                <div>
                  <div className="tv-stat-value">{stats.uniqueSpeakers}</div>
                  <div className="tv-stat-label">Speakers</div>
                </div>
              </div>
              <div className="tv-stat-card">
                <div className="tv-stat-icon amber"><AlertTriangle size={18} /></div>
                <div>
                  <div className="tv-stat-value">{stats.flaggedLines}</div>
                  <div className="tv-stat-label">Flagged Lines</div>
                </div>
              </div>
              <div className="tv-stat-card">
                <div className="tv-stat-icon purple"><Clock size={18} /></div>
                <div>
                  <div className="tv-stat-value">{stats.duration || '—'}</div>
                  <div className="tv-stat-label">Duration</div>
                </div>
              </div>
            </div>

            {/* Metadata Card */}
            {Object.keys(parsed.metadata).length > 0 && (
              <div className="tv-meta-card tv-animate-in">
                <div className="tv-meta-title">
                  {parsed.metadata.meeting_title || 'Meeting Transcript'}
                </div>
                <div className="tv-meta-grid">
                  {parsed.metadata.date && (
                    <div className="tv-meta-item">
                      <span className="tv-meta-label">Date</span>
                      <span className="tv-meta-value">{parsed.metadata.date}</span>
                    </div>
                  )}
                  {parsed.metadata.duration && (
                    <div className="tv-meta-item">
                      <span className="tv-meta-label">Duration</span>
                      <span className="tv-meta-value">{parsed.metadata.duration}</span>
                    </div>
                  )}
                  {participantChips.length > 0 && (
                    <div className="tv-meta-item tv-meta-participants">
                      <span className="tv-meta-label">Participants</span>
                      <div className="tv-meta-value">
                        {participantChips.map((p, i) => {
                          const color = speakerColorMap[p.name] || SPEAKER_PALETTE[i % SPEAKER_PALETTE.length];
                          return (
                            <span key={i} className="tv-participant-chip">
                              <span className="tv-participant-avatar" style={{ background: color.bg }}>
                                {getInitials(p.name)}
                              </span>
                              {p.name}
                              {p.isHost && <span className="tv-host-badge">Host</span>}
                            </span>
                          );
                        })}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Action Items */}
            {parsed.actions.length > 0 && (
              <div className="tv-actions-card tv-animate-in">
                <div className="tv-actions-header">
                  <CheckCircle2 size={14} />
                  Action Items ({parsed.actions.length})
                </div>
                {parsed.actions.map((a, i) => (
                  <div key={i} className="tv-action-item">
                    <span className="tv-action-owner">{a.owner}</span>
                    <span className="tv-action-dash">—</span>
                    <span className="tv-action-text">{a.text}</span>
                  </div>
                ))}
              </div>
            )}

            {/* Speaker Filter Bar */}
            <div className="tv-filter-bar tv-animate-in">
              <span className="tv-filter-label"><Filter size={11} /> Filter</span>
              <button
                className={`tv-filter-all ${!activeSpeaker ? 'active' : ''}`}
                onClick={() => setActiveSpeaker(null)}
              >
                All
              </button>
              {uniqueSpeakers.map(s => {
                const color = speakerColorMap[s.name] || SPEAKER_PALETTE[0];
                return (
                  <button
                    key={s.name}
                    className={`tv-filter-chip ${activeSpeaker === s.name ? 'active' : ''}`}
                    onClick={() => setActiveSpeaker(activeSpeaker === s.name ? null : s.name)}
                  >
                    <span className="tv-filter-dot" style={{ background: color.bg }} />
                    {s.name}
                    <span style={{ opacity: 0.5, fontSize: 10, marginLeft: 2 }}>({s.count})</span>
                  </button>
                );
              })}
            </div>

            {/* Transcript Feed */}
            <div className="tv-feed">
              {filteredTurns.map((turn, idx) => {
                const color = speakerColorMap[turn.speaker] || SPEAKER_PALETTE[0];
                const isEmpty = turn.flags?.includes('EMPTY_TURN');
                const isUnknown = turn.flags?.includes('UNKNOWN');
                const isUnidentified = turn.flags?.includes('UNIDENTIFIED');
                const isDialIn = turn.flags?.includes('DIAL_IN');
                const showBadge = isUnknown || isUnidentified || isDialIn;

                // System annotation
                if (turn.type === 'SYSTEM_ANNOTATION') {
                  return (
                    <div key={idx} className="tv-turn system-turn">
                      <div className="tv-system-content">
                        <span className="tv-system-tag">System</span>
                        {turn.content}
                      </div>
                    </div>
                  );
                }

                // Continuation
                if (turn.type === 'CONTINUATION') {
                  return (
                    <div key={idx} className="tv-turn continuation">
                      <span className="tv-turn-ts" />
                      <span className="tv-turn-speaker-col" />
                      <div className="tv-turn-content">{turn.content}</div>
                    </div>
                  );
                }

                // Normal speech turn
                return (
                  <React.Fragment key={idx}>
                    {idx > 0 && filteredTurns[idx - 1].type !== 'SYSTEM_ANNOTATION' && turn.type !== 'CONTINUATION' && (
                      <div className="tv-turn-divider" />
                    )}
                    <div className={`tv-turn ${isEmpty ? 'empty-turn' : ''}`}>
                      <span className="tv-turn-ts">{turn.timestamp || ''}</span>
                      <div className="tv-turn-speaker-col">
                        <span className="tv-turn-avatar" style={{ background: color.bg }}>
                          {getInitials(turn.speaker)}
                        </span>
                        <span
                          className="tv-turn-speaker-name"
                          style={{ color: color.bg }}
                          onClick={() => setActiveSpeaker(activeSpeaker === turn.speaker ? null : turn.speaker)}
                        >
                          {turn.speaker}
                          {showBadge && (
                            <span className="tv-badge amber">
                              {isDialIn ? 'Dial-In' : isUnidentified ? 'Unidentified' : 'Unknown'}
                            </span>
                          )}
                        </span>
                      </div>
                      <div className="tv-turn-content">
                        {isEmpty ? (
                          <span className="tv-empty-label">
                            <AlertTriangle size={10} /> Empty Turn
                          </span>
                        ) : (
                          turn.content
                        )}
                      </div>
                    </div>
                  </React.Fragment>
                );
              })}
            </div>

            {/* Footer */}
            <div className="tv-footer">
              Parsed {stats.totalTurns} turns from {stats.uniqueSpeakers} speakers · {stats.flaggedLines} flagged
            </div>
          </>
        )}
      </div>
    </div>
  );
}
