"""
Issue Engine Models
===================
Tables:
  - issues            : Core issue records linked to projects
  - issue_actions     : Action items owned by specific people
  - issue_comments    : Audit-friendly comment thread
  - issue_escalations : Escalation records auto-generated by the escalation engine
"""

from sqlalchemy import (
    Column, Integer, String, Text, DateTime, Date,
    ForeignKey, Boolean, Index
)
from sqlalchemy.orm import relationship
from datetime import datetime, timezone

from app.core.database import Base


def _utcnow():
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# issues
# ---------------------------------------------------------------------------

class Issue(Base):
    __tablename__ = "issues"

    id             = Column(Integer, primary_key=True, index=True)
    project_id     = Column(Integer, ForeignKey("projects.id"), nullable=False, index=True)
    upload_id      = Column(Integer, nullable=True)   # optional — links to an upload batch

    # Source traceability
    source_type    = Column(String(20), nullable=False, default="Manual")
    # Allowed: 'Manual' | 'MOM' | 'Tracker'

    # Core fields
    title          = Column(String(255), nullable=False)
    description    = Column(Text, nullable=True)
    owner          = Column(String(100), nullable=False)
    department     = Column(String(100), nullable=True)

    # Priority & severity
    priority       = Column(String(10), nullable=False, default="Medium")
    # Allowed: 'High' | 'Medium' | 'Low'
    severity_score = Column(Integer, nullable=False, default=0)
    # 0–100 manual input; higher = worse

    # Lifecycle
    status         = Column(String(20), nullable=False, default="Open")
    # Stored status: 'Open' | 'In Progress' | 'Closed'
    # Derived (runtime) status: 'Overdue' | 'At Risk' | 'On Track' | 'Closed'

    due_date       = Column(Date, nullable=True)
    meeting_id     = Column(String(100), nullable=True)  # links to meetings table if MOM-derived

    # Timestamps
    created_at     = Column(DateTime(timezone=True), nullable=False, default=_utcnow)
    updated_at     = Column(DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow)
    resolved_at    = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    actions        = relationship("IssueAction",     back_populates="issue", cascade="all, delete-orphan")
    comments       = relationship("IssueComment",    back_populates="issue", cascade="all, delete-orphan")
    escalations    = relationship("IssueEscalation", back_populates="issue", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_issues_project_status", "project_id", "status"),
        Index("ix_issues_project_priority", "project_id", "priority"),
    )


# ---------------------------------------------------------------------------
# issue_actions
# ---------------------------------------------------------------------------

class IssueAction(Base):
    __tablename__ = "issue_actions"

    id                 = Column(Integer, primary_key=True, index=True)
    issue_id           = Column(Integer, ForeignKey("issues.id", ondelete="CASCADE"), nullable=False, index=True)
    action_text        = Column(Text, nullable=False)
    responsible_person = Column(String(100), nullable=True)
    target_date        = Column(Date, nullable=True)
    status             = Column(String(20), nullable=False, default="Pending")
    # Allowed: 'Pending' | 'In Progress' | 'Done'
    created_at         = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    issue = relationship("Issue", back_populates="actions")


# ---------------------------------------------------------------------------
# issue_comments
# ---------------------------------------------------------------------------

class IssueComment(Base):
    __tablename__ = "issue_comments"

    id           = Column(Integer, primary_key=True, index=True)
    issue_id     = Column(Integer, ForeignKey("issues.id", ondelete="CASCADE"), nullable=False, index=True)
    comment_text = Column(Text, nullable=False)
    created_by   = Column(String(100), nullable=False, default="System")
    created_at   = Column(DateTime(timezone=True), nullable=False, default=_utcnow)

    issue = relationship("Issue", back_populates="comments")


# ---------------------------------------------------------------------------
# issue_escalations
# ---------------------------------------------------------------------------

class IssueEscalation(Base):
    __tablename__ = "issue_escalations"

    id               = Column(Integer, primary_key=True, index=True)
    issue_id         = Column(Integer, ForeignKey("issues.id", ondelete="CASCADE"), nullable=False, index=True)
    escalation_level = Column(Integer, nullable=False)
    # 1 = Project Manager, 2 = Department Head, 3 = VP / Admin Queue
    escalated_to     = Column(String(100), nullable=False)
    escalated_at     = Column(DateTime(timezone=True), nullable=False, default=_utcnow)
    reason           = Column(Text, nullable=True)
    is_active        = Column(Boolean, nullable=False, default=True)

    issue = relationship("Issue", back_populates="escalations")

    __table_args__ = (
        # Ensures idempotency — one active escalation per level per issue
        Index("ix_issue_escalations_issue_level", "issue_id", "escalation_level"),
    )
